fix: set winminwidth/height before winwidth/height
nvim-focus/focus.nvim pull request #140
Opened 2023-10-11 03:42 UTC by willothy

fixes #138 (I think)

2023-10-11 19:40 UTC, rustysec commented
using this branch, it fixes my issue with #138

2023-10-12 07:09 UTC, cryptomilk requested changes

2023-10-12 07:09 UTC, cryptomilk commented on lua/focus/modules/resizer.lua
>          vim.o.winminwidth = 1
Can you add code comments please?

2023-10-13 07:31 UTC, willothy commented on lua/focus/modules/resizer.lua
>          vim.o.winminwidth = 1
Done :)

2023-10-13 17:41 UTC, merged